### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by black-strat** [rsquaredacademy/nse2r#46]
1. Experiencing error in nse_stock_quote
    Error in `[.data.frame`(., 1:2) : undefined columns selected
2. Error in nse_stock_code
     Doesn't work

**Comment by aravindhebbali** [comment]
The URL from which the stock code is extracted has changed. Should be a quick fix.

**Comment by black-strat** [comment]
Thanks Aravind!
Have you changed it?

**Comment by aravindhebbali** [comment]
-

> 
> 
> Thanks Aravind!
> Have you changed it?

Yes.. Please install the development version from GitHub and it should work.

**Comment by black-strat** [comment]
working fine now. Thanks!
