### ISSUE TITLE
Fundamentals data on indices

### ISSUE THREAD

**Issue by kathuriarajat** [rsquaredacademy/nse2r#48]
Thanks for the package. Do you plan to add support for scraping fundamentals data for indices. Here's the URL: https://www1.nseindia.com/products/content/equities/indices/historical_pepb.htm

**Comment by aravindhebbali** [comment]
We will look into it and keep you posted. Thanks.

**Comment by kathuriarajat** [comment]
I appreciate a prompt reply! It seems the website prevents scraping fundamentals data. After referring your source code and several other forums, I tried the following:

> url = "https://www1.nseindia.com/products/content/equities/indices/historical_pepb.htm"
> pgsession <-html_session(url)

But, I receive this error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

**Comment by aravindhebbali** [comment]
Yes.. we also got the same error. We are checking with a couple of other R devs to see how this can be implemented. Will keep you in the loop.

**Comment by kathuriarajat** [comment]
A samaritan helped me on GitHub ([link](https://stackoverflow.com/questions/62526944/how-to-know-if-website-is-blocking-scraping-attempt-from-r/62534847#62534847)), and I built a function. You may add it to your repository.

```
get.nse.ratios <- function(index.nse = 'NIFTY 50', date.start = as.Date('2001-01-01'), date.end = as.Date(Sys.time())){
  # url.base <- 'https://www1.nseindia.com/products/content/equities/indices/historical_pepb.htm'
  index.nse <- gsub(' ', '%20', index.nse)
  
  # Split Date range into acceptable range
  max.history.constraint <- 100
  dates.start <- seq.Date(date.start, date.end, by = max.history.constraint)
  data.master <- data.frame()
  # Loop over sub-periods to extract data
  for(fromDate in dates.start){
    toDate <- min(fromDate+(max.history.constraint - 1), as.Date(Sys.Date()))
    
    cat(sprintf('Fetching data from %s to %s \n', as.Date(fromDate), as.Date(toDate)))
    # browser()
    # Reformat dates
    fromDate <- format.Date(as.Date(fromDate), '%d-%m-%Y')
    toDate <- format.Date(as.Date(toDate), '%d-%m-%Y')
    
    # Infer url for sub-period
    url.sub <- sprintf("https://www1.nseindia.com/products/dynaContent/equities/indices/historical_pepb.jsp?indexName=%s&fromDate=%s&toDate=%s&yield1=undefined&yield2=undefined&yield3=undefined&yield4=all", index.nse, fromDate, toDate)
    
    # Scrape table from inferred url
    data.sub <- rvest::html_table(xml2::read_html(url.sub))[[1]]
    
    # Clean the table
    names.columns <- unname(unlist(data.sub[2,]))
    data.clean <- data.sub[3:(nrow(data.sub)-1),]
    colnames(data.clean) <- names.columns
    data.clean$Date <- as.Date(data.clean$Date, format = '%d-%b-%Y')
    cols.num <- names(which(sapply(data.clean, class) == 'character'))
    data.clean[cols.num] <- sapply(data.clean[cols.num],as.numeric)
    
    # Append to master data
    data.master <- rbind(data.master, data.clean)

  }
  
  return(data.master)
}

```

(Disclaimer: Function has not been tested on non-NIFTY 50 NSE indices)
